[phases.setup]
nixPkgs = [
  "nodejs_20",
  "cairo",
  "pango",
  "giflib",
  "libjpeg",
  "libpng",
  "pixman",
  "pkg-config",
  "python3",
  "poppler_utils",
  "freetype",
  "fontconfig",
  "libffi",
  "glib",
  "librsvg"
]
